ALTER TABLE gigs
ALTER COLUMN uri DROP NOT NULL,
ADD COLUMN source VARCHAR(64) NOT NULL DEFAULT 'songkick',
ADD COLUMN external_link VARCHAR(256) NULL,
ADD COLUMN author_id varchar(36) REFERENCES users(id) ON DELETE SET NULL;
